'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
export default function KasManager(){
  const [kas,setKas]=useState<any[]>([])
  const [form,setForm]=useState({jenis:'MASUK',nominal:0,kategori:'Iuran',keterangan:''})
  const [show,setShow]=useState(false)
  const load=async()=>{ const { data } = await supabase.from('kas').select('*').order('tanggal',{ascending:false}); setKas(data||[]) }
  useEffect(()=>{load()},[])
  const save=async()=>{ if(!form.nominal) return alert('Nominal wajib'); await supabase.from('kas').insert([{tanggal:new Date().toISOString().split('T')[0],jenis:form.jenis,nominal:form.nominal,kategori:form.kategori,keterangan:form.keterangan}]); setForm({jenis:'MASUK',nominal:0,kategori:'Iuran',keterangan:''}); setShow(false); load() }
  const totalMasuk=kas.filter(k=>k.jenis==='MASUK').reduce((a,b)=>a+b.nominal,0)
  const totalKeluar=kas.filter(k=>k.jenis==='KELUAR').reduce((a,b)=>a+b.nominal,0)
  const saldo=totalMasuk-totalKeluar
  return (<div className="space-y-4"><div className="grid grid-cols-3 gap-3"><div className="card rounded-[20px] p-5"><div className="text-[10px] text-slate-500">MASUK</div><div className="text-[18px] font-black text-emerald-400">Rp {totalMasuk.toLocaleString('id-ID')}</div></div><div className="card rounded-[20px] p-5"><div className="text-[10px] text-slate-500">KELUAR</div><div className="text-[18px] font-black text-red-400">Rp {totalKeluar.toLocaleString('id-ID')}</div></div><div className="card rounded-[20px] p-5 bg-white text-black"><div className="text-[10px]">SALDO</div><div className="text-[18px] font-black">Rp {saldo.toLocaleString('id-ID')}</div></div></div><div className="card rounded-[24px] p-6 flex justify-between"><h3 className="font-bold">Kas - {kas.length}</h3><button onClick={()=>setShow(!show)} className="bg-white text-black rounded-full px-5 py-2 text-[12px] font-bold">+ Transaksi</button></div>{show && <div className="card rounded-[24px] p-5 grid grid-cols-2 gap-3"><select value={form.jenis} onChange={e=>setForm({...form,jenis:e.target.value})} className="bg-[#0F1220] border border-[#2A2F4A] rounded-full px-4 py-2.5 text-[12px]"><option value="MASUK">MASUK</option><option value="KELUAR">KELUAR</option></select><input type="number" value={form.nominal} onChange={e=>setForm({...form,nominal:parseInt(e.target.value)||0})} placeholder="Nominal" className="bg-[#0F1220] border border-[#2A2F4A] rounded-full px-4 py-2.5 text-[12px]" /><input value={form.kategori} onChange={e=>setForm({...form,kategori:e.target.value})} placeholder="Kategori" className="bg-[#0F1220] border border-[#2A2F4A] rounded-full px-4 py-2.5 text-[12px]" /><input value={form.keterangan} onChange={e=>setForm({...form,keterangan:e.target.value})} placeholder="Keterangan" className="col-span-2 bg-[#0F1220] border border-[#2A2F4A] rounded-full px-4 py-2.5 text-[12px]" /><button onClick={save} className="col-span-2 bg-violet-600 text-white rounded-full py-2.5 text-[12px] font-bold">Simpan</button></div>}<div className="card rounded-[24px] p-6"><div className="space-y-2">{kas.map((k:any)=><div key={k.id} className="flex justify-between bg-[#0F1220] rounded-full px-5 py-3"><div><div className="text-[13px]">{k.kategori} - {k.keterangan} <span className={`ml-2 text-[10px] px-2 py-0.5 rounded-full ${k.jenis==='MASUK'?'bg-emerald-500/20 text-emerald-400':'bg-red-500/20 text-red-400'}`}>{k.jenis}</span></div><div className="text-[10px] text-slate-500">{k.tanggal} • Rp {k.nominal?.toLocaleString()}</div></div></div>)}</div></div></div>)
}
